### ISSUE TITLE
LiquidCrystal_I2C Xtension

### ISSUE THREAD

**Issue by blascarr** [VasilKalchev/LiquidMenu#5]
Hi.

This repository is really great. 
I am using it with other library for the same **LCD** connected with **I2C** and [LiquidCrystal_I2C](https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library) library.
It works exactly with the same functions of standard **LyquidCrystal librar**y; however with **I2C** connection is simple and fast to connect.

I have created another library replacing the object and the library calls, and it compiles. But the pointer for "**__p_liquidCrystal_**" attribute of **LiquidMenu Class** does not work calling outside setup and loop like global variables.

However, inside **setup**  i create a **local LiquidMenu object** and  it works really great and my lcd respond... But i need a global object to manipulate it inside **loop** and other **custom functions**.

I´m going crazy, because i don´t really understand what is the main problem. I need some help for this xtension and create a fork.

Greetings.

**Comment by VasilKalchev** [comment]
Sorry for the huge delay.

**The problem comes from the difference between the constructor of the original _LiquidCrystal_ library and the constructor of the _LiquidCrystal_I2C_ library.**

The _LiquidCrystal_ library calls it's public method `begin()` (used again later in `setup()`) from the constructor which allows method calls on the object.
The _LiquidCrystal_I2C_ library doesn't call it, and for some reason calling the object's methods before `begin()` breaks the object.

So when using _LiquidCrystal_I2C_, my _LiquidMenu_ constructor calls `LiquidCrystal_I2C::createChar(int, int[])` before `LiquidCrystal_I2C::begin()` is called, which breaks the not fully initialized _LiquidCrystal_I2C_ object.

I tried calling the `begin()` method from the _LiquidCrystal_I2C_ constructor, but that broke the object too. I also tried modifying the code in the `LiquidCrystal_I2C::begin()` method, but I couldn't make it to work.

The way to make it work without breaking the _LiquidMenu_ API is to move the 3 calls:
```
// LiquidMenu/src/LiquidMenu.cpp
    ...
    _p_liquidCrystal->createChar(15, symbol::rightFocus);
    _p_liquidCrystal->createChar(14, symbol::leftFocus);
    _p_liquidCrystal->createChar(13, symbol::customFocus);
    ...
```
and the "focus" variables:
```
// LiquidMenu/src/symbols.h
    namespace symbol {
    uint8_t rightFocus[8] = {
      0b00000 ,0b00100, 0b01000, 0b11111, 0b01000, 0b00100, 0b00000, 0b00000
    };
    uint8_t leftFocus[8] = {
      0b00000, 0b00100, 0b00010, 0b11111, 0b00010, 0b00100, 0b00000,0b00000
    };
    uint8_t customFocus[8] = {
      0b00000, 0b00000, 0b01110, 0b01110, 0b01110, 0b00000, 0b00000, 0b00000
    };
    } //namespace symbol
```
to the end of the `LiquidCrystal_I2C::begin()` method:
```
// LiquidCrystal_I2C/LiquidCrystal_I2C.cpp
    ...
    // set the entry mode
    command(LCD_ENTRYMODESET | _displaymode);

    home();

    createChar(15, symbol::rightFocus);
    createChar(14, symbol::leftFocus);
    createChar(13, symbol::customFocus);
  }
  ...
```
and the variables in the same file before the constructor. Other solution will be to use a different I2C library if there is available.
